# Generated by Django 2.2.3 on 2019-09-16 14:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190916_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagories',
            field=models.ManyToManyField(blank=True, to='blog.Catagory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
